{% set name = "screenFetch" %}
{% set version = "3.9.1" %}
{% set author = "KittyKatt" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: aa97dcd2a8576ae18de6c16c19744aae1573a3da7541af4b98a91930a30a3178

build:
  skip: True  # [win]
  number: 0

requirements:
  build:
    - coreutils
  run:
    - bash

test:
  commands:
    - screenfetch -V

about:
  home: https://github.com/KittyKatt/screenFetch
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: COPYING
  summary: "Generate ASCII art with terminal, shell, and OS info"
  description: | 
    screenFetch is a shell script that generates ASCII art with terminal, shell, and OS info.
  dev_url: https://github.com/KittyKatt/screenFetch

extra:
  recipe-maintainers:
    - eunos-1128
