{% set name = "screenFetch" %}
{% set version = "3.9.9" %}
{% set author = "KittyKatt" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 65ba578442a5b65c963417e18a78023a30c2c13a524e6e548809256798b9fb84

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - coreutils
  run:
    - bash

test:
  commands:
    - screenfetch -V

about:
  home: https://github.com/KittyKatt/screenFetch
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: COPYING
  summary: "Generate ASCII art with terminal, shell, and OS info"
  description: |
    screenFetch is a shell script that generates ASCII art with terminal, shell, and OS info.
  dev_url: https://github.com/KittyKatt/screenFetch

extra:
  recipe-maintainers:
    - eunos-1128
