context:
  name: screenFetch
  version: "3.9.9"
  author: KittyKatt

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ author }}/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 65ba578442a5b65c963417e18a78023a30c2c13a524e6e548809256798b9fb84

build:
  noarch: generic
  number: 1
  script: |
    set -exo pipefail
    install -D -m 755 screenfetch-dev ${{ PREFIX }}/bin/screenfetch
    install -D -m 644 screenfetch.1 ${{ PREFIX }}/share/man/man1/screenfetch.1

requirements:
  build:
    - coreutils
  run:
    - bash

tests:
  - script:
    - ${{ name|lower }} -V

about:
  homepage: https://github.com/${{ author }}/${{ name }}
  repository: https://github.com/${{ author }}/${{ name }}
  documentation: https://github.com/${{ version }}/${{ name }}/blob/v${{ version }}/README.mkdn
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: "Generate ASCII art with terminal, shell, and OS info"
  description: |
    screenFetch is a shell script that generates ASCII art with terminal, shell, and OS info.

extra:
  recipe-maintainers:
    - eunos-1128
